### ISSUE TITLE
Can you support kebab-case?

### ISSUE THREAD

**Issue by namhokim** [coveooss/spring-boot-parameter-store-integration#160]
In Spring Boot, YAML property allows Camel case, kebab case, or underscore notation.
But this library support only Camel case.
Can you support kebab-case notation?

ref. https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding

**Comment by fredboutin** [comment]
You mean instead of AWS' slash '/' ? This is intended since AWS use / in parameter store and it gives us a handle to determine if the parameter has to be fetched from AWS Parameter Store. If we support something else (like kebab-case, camelCase) then *every* single property is going to be looked up in the param store and you will for sure be throttled. This means every time the application hits an `@Value` it's going to make a call to the param store. Spring uses this a lot internally so it means a lot of calls.

**Comment by namhokim** [comment]
No, I intended like below example:

```yaml
aws-parameter-store-property-source:
  enabled: true
  halt-boot: true
  multi-region:
    ssm-client:
      regions: ap-northeast-1
```
not only:
```yaml
awsParameterStorePropertySource:
  enabled: true
  haltBoot: true
  multiRegion:
    ssmClient:
      regions: ap-northeast-1
```
